version: "3.3"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./data:/var/lib/odoo
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
